# Generated by Django 5.1.4 on 2025-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, '1stCategory'), (1, '2stCategory'), (2, '3stCategory')], default=0, max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, '1stCategory'), (1, '2stCategory'), (2, '3stCategory')], default=0),
        ),
    ]
