# Generated by Django 5.1.4 on 2025-01-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_role_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Category',
        ),
    ]
